// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_1/models/environment_variables.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: EnvironmentVariables.firebaseApiKeyWeb,
    appId: EnvironmentVariables.firebaseAppIdWeb,
    messagingSenderId: EnvironmentVariables.firebaseMessengerSenderId,
    projectId: EnvironmentVariables.firebaseProjectId,
    authDomain: EnvironmentVariables.firebaseAuthDomain,
    storageBucket: EnvironmentVariables.firebaseStorageBucket,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: EnvironmentVariables.firebaseApiKeyAndroid,
    appId: EnvironmentVariables.firebaseAppIdAndroid,
    messagingSenderId: EnvironmentVariables.firebaseMessengerSenderId,
    projectId: EnvironmentVariables.firebaseProjectId,
    storageBucket: EnvironmentVariables.firebaseStorageBucket,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: EnvironmentVariables.firebaseApiKeyIos,
    appId: EnvironmentVariables.firebaseAppIdIos,
    messagingSenderId: EnvironmentVariables.firebaseMessengerSenderId,
    projectId: EnvironmentVariables.firebaseProjectId,
    storageBucket: EnvironmentVariables.firebaseStorageBucket,
    iosClientId: EnvironmentVariables.firebaseClientIdIos,
    iosBundleId: EnvironmentVariables.firebaseBundleIdIos,
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: EnvironmentVariables.firebaseApiKeyIos,
    appId: EnvironmentVariables.firebaseAppIdIos,
    messagingSenderId: EnvironmentVariables.firebaseMessengerSenderId,
    projectId: EnvironmentVariables.firebaseProjectId,
    storageBucket: EnvironmentVariables.firebaseStorageBucket,
    iosClientId: EnvironmentVariables.firebaseClientIdIos,
    iosBundleId: EnvironmentVariables.firebaseBundleIdIos,
  );
}
