// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcPEektAGS9skikc_WwjMlXm_tkJ0Tduk',
    appId: '1:570045593691:web:239983ea182d28feb6677e',
    messagingSenderId: '570045593691',
    projectId: 'flutterauth-aa259',
    authDomain: 'flutterauth-aa259.firebaseapp.com',
    storageBucket: 'flutterauth-aa259.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKRukHKkGzVidadE9gvqA35OlBt3J_tnw',
    appId: '1:570045593691:android:289eb01a77a04872b6677e',
    messagingSenderId: '570045593691',
    projectId: 'flutterauth-aa259',
    storageBucket: 'flutterauth-aa259.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt9rkM4-NegMVUkz_-NZTwLP0ZI2T40d0',
    appId: '1:570045593691:ios:668626fd11dbdd2bb6677e',
    messagingSenderId: '570045593691',
    projectId: 'flutterauth-aa259',
    storageBucket: 'flutterauth-aa259.appspot.com',
    iosClientId: '570045593691-41v714pd70935ehnfd9689vub2fhm4l1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt9rkM4-NegMVUkz_-NZTwLP0ZI2T40d0',
    appId: '1:570045593691:ios:668626fd11dbdd2bb6677e',
    messagingSenderId: '570045593691',
    projectId: 'flutterauth-aa259',
    storageBucket: 'flutterauth-aa259.appspot.com',
    iosClientId: '570045593691-41v714pd70935ehnfd9689vub2fhm4l1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase1',
  );
}
